name: CDN Asset Cleanup (Manual)

on:
  workflow_dispatch:
    inputs:
      keep_versions:
        description: "How many latest versions to keep?"
        required: true
        default: "5"
permissions:
  contents: write
jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Show cleanup config
        run: |
          echo "Keeping latest ${{ github.event.inputs.keep_versions }} versions"

      - name: Cleanup old assets
        run: |
          KEEP=${{ github.event.inputs.keep_versions }}

          echo "Finding version folders..."
          ls banner || exit 0

          echo "Deleting old versions..."
          ls -dt banner/v* | tail -n +$((KEEP+1)) | xargs -r rm -rf

          echo "Cleanup completed âœ…"

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          if git diff --cached --quiet; then
          echo "No changes to commit"
          else
          git commit -m "Manual CDN cleanup"
          git push
          fi
